---
login:
  url: http://login-rlichti-eu.berlin.dbcs.db.de/login

cookie:
  name: javasession
  path: /
  domain: reproducer-rlichti-eu.berlin.dbcs.db.de
  isSecure: false
  httpOnly: true

quarkus:
  container-image:
    group: klenkes74
    name: rfe600-reproducer
    version: 1.0.0-SNAPSHOT
    registry: quay.io
    username: klenkes74
    build: true
    push: false

  openshift:
    part-of: RFE-600
    env-vars:
      "login.url":
        value: http://login-rlichti-eu.berlin.dbcs.db.de/login
      "cookie.name":
        value: javasession
      "cookie.path":
        value: /
      "cookie.domain":
        value: reproducer-rlichti-eu.berlin.dbcs.db.de
      "cookie.isSecure":
        value: false
      "cookie.httpOnly":
        value: true
    replicas: 2
    readiness-probe:
      initial-delay: 5s
      period: 60s
    liveness-probe:
      initial-delay: 5s
      period: 60s

"%dev":
  login:
    url: http://localhost:8080/login
  resource:
    port: ":8080"
  cookie:
    domain: localhost

"%test":
  login:
    url: http://localhost:8081/login
  resource:
    port: ":8080"
  cookie:
    domain: localhost
    name: session